# Generated by Django 3.2.16 on 2022-12-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(default=0)),
                ('start_round_time', models.IntegerField(default=150, verbose_name='начальное время на раунд')),
                ('started', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('good_answers', models.IntegerField(default=0)),
                ('bad_answers', models.IntegerField(default=0)),
                ('brought_in_bank', models.IntegerField(default=0)),
                ('out_of_game', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(default=0)),
                ('now_bank', models.IntegerField(default=0)),
                ('end_time', models.DateTimeField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamemember')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamequestion')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='questions',
            field=models.ManyToManyField(to='game.GameQuestion', verbose_name='вопросы'),
        ),
    ]
