# Generated by Django 3.2.16 on 2022-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
