# Generated by Django 3.2.16 on 2022-12-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_gamemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamemember',
            name='out_of_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='bank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='round_time',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='gamemember',
            name='bad_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamemember',
            name='brought_in_bank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamemember',
            name='good_answers',
            field=models.IntegerField(default=0),
        ),
    ]
