# Generated by Django 3.2.16 on 2022-12-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameround_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameround',
            name='final',
            field=models.BooleanField(default=False),
        ),
    ]
