# Generated by Django 3.2.16 on 2022-12-14 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameround_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_round_time',
            field=models.IntegerField(default=150, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(1)], verbose_name='начальное время на раунд'),
        ),
    ]
