# Generated by Django 3.2.16 on 2022-12-15 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_start_round_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_round_time',
            field=models.IntegerField(default=150, validators=[django.core.validators.MaxValueValidator(1800), django.core.validators.MinValueValidator(120)], verbose_name='начальное время на раунд'),
        ),
    ]
