# Generated by Django 3.2.16 on 2022-12-12 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20221212_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_round_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='round_time',
        ),
        migrations.RemoveField(
            model_name='gamemember',
            name='member_id_in_game',
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_bank', models.IntegerField(default=0)),
                ('round_now_bank', models.IntegerField(default=0)),
                ('round_time', models.IntegerField(default=150)),
                ('end_round_time', models.FloatField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
