# Generated by Django 3.2.16 on 2022-12-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20221212_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameround',
            old_name='round_bank',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='gameround',
            old_name='round_now_bank',
            new_name='now_bank',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='end_round_time',
        ),
        migrations.RemoveField(
            model_name='gameround',
            name='round_time',
        ),
        migrations.AddField(
            model_name='game',
            name='start_round_time',
            field=models.IntegerField(default=150, verbose_name='начальное время на раунд'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
