# Generated by Django 3.2.16 on 2022-12-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20221215_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionInGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamequestion')),
            ],
        ),
    ]
