# Generated by Django 3.2.16 on 2022-12-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_questioningame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_filter',
            field=models.CharField(choices=[('id', 'По порядку'), ('?', 'Рандомный порядок')], default='?', max_length=2),
        ),
    ]
