# Generated by Django 3.2.16 on 2022-12-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_rename_round_filter_game_question_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='question_filter',
            field=models.CharField(choices=[('id', 'По порядку'), ('?', 'Рандомный порядок')], default='?', max_length=2, verbose_name='Сортировка вопросов'),
        ),
    ]
