# Generated by Django 3.2.16 on 2022-12-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_question_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='question_filter',
            field=models.CharField(choices=[('?', 'рандомный порядок'), ('question', 'вопросы в алфавитном порядке '), ('pk', 'по порядку')], default='?', max_length=8, verbose_name='cортировка вопросов'),
        ),
    ]
